package tavily

// SearchRequest represents the request for the Tavily API.
type SearchRequest struct {
	Query                    string `json:"query"`                      // The search query to execute with Tavily.
	AutoParameters           bool   `json:"auto_parameters"`            // When auto_parameters is enabled, Tavily automatically configures search parameters based on your query's content and intent.
	IncludeAnswer            bool   `json:"include_answer"`             // Include an LLM-generated answer to the provided query.
	IncludeRawContent        bool   `json:"include_raw_content"`        // Include the cleaned and parsed HTML content of each search result.
	IncludeImages            bool   `json:"include_images"`             // Perform an image search and include the results in the response.
	IncludeImageDescriptions bool   `json:"include_image_descriptions"` // Includes descriptive text for each image.
	MaxResults               int    `json:"max_results"`                // The maximum number of search results to return. (Max: 20)
}

// SearchResponse represents the response from the Tavily API.
type SearchResponse struct {
	Query          string            `json:"query"`           // The search query that was executed.
	Answer         string            `json:"answer"`          // A short answer to the user's query, generated by an LLM.
	Images         []ImageResult     `json:"images"`          // List of query-related images.
	Results        []SiteResult      `json:"results"`         // A list of sorted search results, ranked by relevancy.
	AutoParameters map[string]string `json:"auto_parameters"` // A dictionary of the selected auto_parameters.
	RequestID      string            `json:"request_id"`      // A unique request identifier
}

// SiteResult represents a single search result from the Tavily API.
type SiteResult struct {
	Title      string  `json:"title"`       // The title of the search result.
	URL        string  `json:"url"`         // The URL of the search result.
	Content    string  `json:"content"`     // A short description of the search result.
	Score      float64 `json:"score"`       // The relevance score of the search result.
	RawContent string  `json:"raw_content"` // The cleaned and parsed HTML content of the search result.
	Favicon    string  `json:"favicon"`     // The favicon URL for the result.
}

// ImageResult represents a single image result from the Tavily API.
type ImageResult struct {
	URL         string `json:"url"`         // The URL of the image.
	Description string `json:"description"` // A short description of the image.
}
